### ISSUE TITLE
Build crashes running IDE

### ISSUE THREAD

**Issue by Bananeweizen** [eclipse-cbi/targetplatform-dsl#135]
When the auto-build is enabled or when the project `org.eclipse.cbi.targetplatform` is built via Projects>Clean, the running IDE is terminated. AFAIK that's caused by the exec-maven-plugin being executed in the same JVM, and some exceptions in the MWE workflow not being caught anywhere.
If I use eclipsec instead of eclipse.exe, then I can see these exceptions (which are not in the log):
```
0    INFO  XtextGenerator     - Initializing Xtext generator
7    INFO  StandaloneSetup    - Adding generated EPackage 'org.eclipse.xtext.common.types.TypesPackage'
158  INFO  StandaloneSetup    - Registering project org.eclipse.cbi.targetplatform at 'file:/C:/dev/tpd/git/targetplatform-dsl/org.eclipse.cbi.targetplatform/'
159  INFO  StandaloneSetup    - Registering project org.eclipse.cbi.targetplatform.tests at 'file:/C:/dev/tpd/git/targetplatform-dsl/org.eclipse.cbi.targetplatform.tests/'
160  INFO  StandaloneSetup    - Registering project org.eclipse.cbi.targetplatform.ide at 'file:/C:/dev/tpd/git/targetplatform-dsl/org.eclipse.cbi.targetplatform.ide/'
161  INFO  StandaloneSetup    - Registering project org.eclipse.cbi.targetplatform.ui at 'file:/C:/dev/tpd/git/targetplatform-dsl/org.eclipse.cbi.targetplatform.ui/'
161  INFO  StandaloneSetup    - Registering project org.eclipse.cbi.targetplatform.ui.tests at 'file:/C:/dev/tpd/git/targetplatform-dsl/org.eclipse.cbi.targetplatform.ui.tests/'
178  INFO  StandaloneSetup    - Using resourceSet registry. The registered Packages will not be registered in the global EPackage.Registry.INSTANCE!
915  ERROR XtextGeneratorResourceSetInitializer - Could not load XcoreLang.xcore.
org.eclipse.emf.ecore.resource.impl.ResourceSetImpl$1DiagnosticWrappedException: java.io.IOException: The path '/org.eclipse.emf.ecore.xcore.lib/model/XcoreLang.xcore' is unmapped
        at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.handleDemandLoadException(ResourceSetImpl.java:319)
        at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoadHelper(ResourceSetImpl.java:278)
        at org.eclipse.xtext.resource.XtextResourceSet.getResource(XtextResourceSet.java:266)
        at org.eclipse.xtext.xtext.generator.XtextGeneratorResourceSetInitializer.ensureResourceCanBeLoaded(XtextGeneratorResourceSetInitializer.java:107)
        at org.eclipse.xtext.xtext.generator.XtextGeneratorResourceSetInitializer.loadResource(XtextGeneratorResourceSetInitializer.java:50)        at org.eclipse.xtext.xtext.generator.XtextGeneratorResourceSetInitializer.lambda$initialize$0(XtextGeneratorResourceSetInitializer.java:42)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.eclipse.xtext.xtext.generator.XtextGeneratorResourceSetInitializer.initialize(XtextGeneratorResourceSetInitializer.java:41)
        at org.eclipse.xtext.xtext.generator.XtextGeneratorLanguage.initialize(XtextGeneratorLanguage.java:202)
        at org.eclipse.xtext.xtext.generator.StandardLanguage.initialize(StandardLanguage.java:167)
        at org.eclipse.xtext.xtext.generator.XtextGenerator.initialize(XtextGenerator.java:189)
        at org.eclipse.xtext.xtext.generator.XtextGenerator.checkConfigurationInternal(XtextGenerator.java:157)
        at org.eclipse.emf.mwe.core.lib.AbstractWorkflowComponent2.checkConfiguration(AbstractWorkflowComponent2.java:23)
        at org.eclipse.emf.mwe.core.lib.Mwe2Bridge.preInvoke(Mwe2Bridge.java:69)
        at org.eclipse.emf.mwe.core.lib.AbstractWorkflowComponent.preInvoke(AbstractWorkflowComponent.java:208)
        at org.eclipse.emf.mwe2.runtime.workflow.AbstractCompositeWorkflowComponent.preInvoke(AbstractCompositeWorkflowComponent.java:31)
        at org.eclipse.emf.mwe2.runtime.workflow.Workflow.run(Workflow.java:20)
        at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:103)
        at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:63)
        at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:53)
        at org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher.run(Mwe2Launcher.java:78)
        at org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher.main(Mwe2Launcher.java:36)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:279)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.io.IOException: The path '/org.eclipse.emf.ecore.xcore.lib/model/XcoreLang.xcore' is unmapped
        at org.eclipse.emf.ecore.resource.impl.PlatformResourceURIHandlerImpl.createInputStream(PlatformResourceURIHandlerImpl.java:584)
        at org.eclipse.emf.ecore.resource.impl.ExtensibleURIConverterImpl.createInputStream(ExtensibleURIConverterImpl.java:358)
        at org.eclipse.xtext.resource.XtextResourceSet$1.createInputStream(XtextResourceSet.java:299)
        at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1314)
        at org.eclipse.xtext.resource.persistence.StorageAwareResource.load(StorageAwareResource.java:64)
        at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoad(ResourceSetImpl.java:259)
        at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoadHelper(ResourceSetImpl.java:274)
        ... 22 more
922  ERROR Mwe2Launcher       - Problems running workflow org.eclipse.cbi.GenerateTargetPlatform: java.io.IOException: The path '/org.eclipse.cbi.targetplatform.model/src/main/resources/TargetPlatform.xcore' is unmapped
java.lang.RuntimeException: Problems running workflow org.eclipse.cbi.GenerateTargetPlatform: java.io.IOException: The path '/org.eclipse.cbi.targetplatform.model/src/main/resources/TargetPlatform.xcore' is unmapped
        at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:105)
        at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:63)
        at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:53)
        at org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher.run(Mwe2Launcher.java:78)
        at org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher.main(Mwe2Launcher.java:36)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:279)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.eclipse.emf.ecore.resource.impl.ResourceSetImpl$1DiagnosticWrappedException: java.io.IOException: The path '/org.eclipse.cbi.targetplatform.model/src/main/resources/TargetPlatform.xcore' is unmapped
        at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.handleDemandLoadException(ResourceSetImpl.java:319)
        at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoadHelper(ResourceSetImpl.java:278)
        at org.eclipse.xtext.resource.XtextResourceSet.getResource(XtextResourceSet.java:266)
        at org.eclipse.xtext.xtext.generator.XtextGeneratorResourceSetInitializer.loadResource(XtextGeneratorResourceSetInitializer.java:51)        at org.eclipse.xtext.xtext.generator.XtextGeneratorResourceSetInitializer.lambda$initialize$0(XtextGeneratorResourceSetInitializer.java:42)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.eclipse.xtext.xtext.generator.XtextGeneratorResourceSetInitializer.initialize(XtextGeneratorResourceSetInitializer.java:41)
        at org.eclipse.xtext.xtext.generator.XtextGeneratorLanguage.initialize(XtextGeneratorLanguage.java:202)
        at org.eclipse.xtext.xtext.generator.StandardLanguage.initialize(StandardLanguage.java:167)
        at org.eclipse.xtext.xtext.generator.XtextGenerator.initialize(XtextGenerator.java:189)
        at org.eclipse.xtext.xtext.generator.XtextGenerator.checkConfigurationInternal(XtextGenerator.java:157)
        at org.eclipse.emf.mwe.core.lib.AbstractWorkflowComponent2.checkConfiguration(AbstractWorkflowComponent2.java:23)
        at org.eclipse.emf.mwe.core.lib.Mwe2Bridge.preInvoke(Mwe2Bridge.java:69)
        at org.eclipse.emf.mwe.core.lib.AbstractWorkflowComponent.preInvoke(AbstractWorkflowComponent.java:208)
        at org.eclipse.emf.mwe2.runtime.workflow.AbstractCompositeWorkflowComponent.preInvoke(AbstractCompositeWorkflowComponent.java:31)
        at org.eclipse.emf.mwe2.runtime.workflow.Workflow.run(Workflow.java:20)
        at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:103)
        ... 6 more
Caused by: java.io.IOException: The path '/org.eclipse.cbi.targetplatform.model/src/main/resources/TargetPlatform.xcore' is unmapped
        at org.eclipse.emf.ecore.resource.impl.PlatformResourceURIHandlerImpl.createInputStream(PlatformResourceURIHandlerImpl.java:584)
        at org.eclipse.emf.ecore.resource.impl.ExtensibleURIConverterImpl.createInputStream(ExtensibleURIConverterImpl.java:358)
        at org.eclipse.xtext.resource.XtextResourceSet$1.createInputStream(XtextResourceSet.java:299)
        at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1314)
        at org.eclipse.xtext.resource.persistence.StorageAwareResource.load(StorageAwareResource.java:64)
        at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoad(ResourceSetImpl.java:259)
        at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoadHelper(ResourceSetImpl.java:274)
        ... 21 more
```
Is there anything simple we can do to make the workflow run in its own JVM? Is there something to report to the M2E project (maybe we can catch something from within its launch)?

**Comment by merks** [comment]
What a nightmare.  I don't even know why this has to run when the setup runs it the MWE already.   The simplest thing here is just to remove all the m2e natures/builders...

**Comment by merks** [comment]
This avoids the problem.  The development environment is simply not usable with all these crashes.
