### ISSUE TITLE
Exception occurred when trying to update a target definition

### ISSUE THREAD

**Issue by glefur** [eclipse-cbi/targetplatform-dsl#53]
java.lang.IllegalStateException: Profile TARGET_DEFINITION:resource:/fr.obeo.presales.federation.environment/smartea.target is not current. Expected timestamp 1418735799543 but was 1418735783004.
    at org.eclipse.equinox.internal.p2.engine.SimpleProfileRegistry.lockProfile(SimpleProfileRegistry.java:758)
    at org.eclipse.equinox.internal.p2.engine.Engine.perform(Engine.java:67)
    at org.eclipse.equinox.internal.p2.engine.Engine.perform(Engine.java:44)
    at org.eclipse.pde.internal.core.target.P2TargetUtils.resolveWithPlanner(P2TargetUtils.java:928)
    at org.eclipse.pde.internal.core.target.P2TargetUtils.synchronize(P2TargetUtils.java:718)
    at org.eclipse.pde.internal.core.target.IUBundleContainer.resolveBundles(IUBundleContainer.java:254)
    at org.eclipse.pde.internal.core.target.AbstractBundleContainer.resolve(AbstractBundleContainer.java:77)
    at org.eclipse.pde.internal.core.target.TargetDefinition.resolve(TargetDefinition.java:262)
    at fr.obeo.releng.targetplatform.ui.handler.PDEIntegration.trySetTargetPlatform(PDEIntegration.java:68)
    at fr.obeo.releng.targetplatform.ui.handler.PDEIntegration.setTargetPlatform(PDEIntegration.java:55)
    at fr.obeo.releng.targetplatform.ui.handler.ConvertTargetPlatformJob.run(ConvertTargetPlatformJob.java:89)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

**Comment by merks** [comment]
I've seen similar/related problems reported against PDE:

https://github.com/eclipse-pde/eclipse.pde/issues/310

I don't think this problem can be fixed, but if I could reproduce the problem, I'd be able to determine where the problem needs to be fixed.

If you have such steps, please share them.
