### ISSUE TITLE
Cannot find a service reference to org.eclipse.equinox.p2.core.IProvisioningAgentProvider

### ISSUE THREAD

**Issue by peugene** [eclipse-cbi/targetplatform-dsl#94]
Actually, i have a build that works fine with TPD and Eclipse Oxygen.
I try to migrate to the last release of Eclipse : 2019-09.

Cette ligne de commande est lancé par le build Maven : 
-consoleLog, -application, org.eclipse.cbi.targetplatform.tpd.converter, my.tpd

The build failed with this error message : 
`!ENTRY org.eclipse.cbi.targetplatform 4 0 2019-10-16 14:43:27.891
!MESSAGE Cannot find a service reference to org.eclipse.equinox.p2.core.IProvisioningAgentProvider

!ENTRY org.eclipse.osgi 4 0 2019-10-16 14:43:27.991
!MESSAGE Application error
!STACK 1
com.google.inject.CreationException: Guice creation errors:

1) null returned by binding at org.eclipse.xtext.service.MethodBasedModule.configure(MethodBasedModule.java:75)
 but org.eclipse.cbi.targetplatform.validation.TargetPlatformValidator.provisioningAgent is not @Nullable
  while locating org.eclipse.equinox.p2.core.IProvisioningAgent
    for field at org.eclipse.cbi.targetplatform.validation.TargetPlatformValidator.provisioningAgent(Unknown Source)
  at org.eclipse.xtext.service.MethodBasedModule.configure(MethodBasedModule.java:57)
  while locating org.eclipse.cbi.targetplatform.validation.TargetPlatformValidator`

I try the build with last converter : org.eclipse.cbi.targetplatform.tpd.converter and with the legacy converter : fr.obeo.releng.targetplatform.targetPlatform.converter

The build failed with the two version of the TPD

T

**Comment by bvarnai** [comment]
This means the Eclipse services are not properly initialized. If you are using a run configuration, you need add some plugins. Goto "Plug-ins" tab in the run configuration editor (if you see an empty list, select "plugins selected below only" and check the converter plugin "org.eclipse.cbi.targetplatform". You might need to use "Add Required Plug-ins" if some dependencies are missing.
```xml 
<plugin id="org.eclipse.core.runtime" autoStart="true" startLevel="2" />
<plugin id="org.eclipse.equinox.ds" autoStart="true" startLevel="3" />
<plugin id="org.eclipse.equinox.event" autoStart="true" startLevel="3" />
```
This taken form a product configuration, but the same attributes can be set in the run configuration editor. This should eliminate the error above.
